### ISSUE TITLE
Treffen No. 1

### ISSUE THREAD

**Issue by yyazgan** [ProPra16/programmierpraktikum-abschlussprojekt-pwnyhof#8]
Hallo liebe Gruppe,

ich betreue euch. Bitte kommt doch in meine Übung am Freitag um 16:30 Uhr. 

Viele Grüße 

Yasin

**Comment by lordfurafura** [comment]
Hallo Yasin,

Ich kann am Freitag leider nicht zu dem Treffen kommen (meine Gruppe weiß schon Bescheid und gibt mir Bescheid was besprochen wurde), ich hoffe das ist okay.

Liebe Grüße,

Yannick

**Comment by ObiHanKenobi** [comment]
ichkann nicht. bin da schon auf der arbeit. teammates wissen bescheid

**Comment by chede100** [comment]
In welchem Raum findet die Übung denn statt?

**Comment by yyazgan** [comment]
Da wo die Übungen stattfinden. Nebenan sind die Mathekästen. Müsste 25.13.00.81 sein.
